lib/chatlag_web/router.ex
defmodule ChatlagWeb.Router do
  use ChatlagWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlugForwardedPeer
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  pipeline :admin do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :protected do
    plug Chatlag.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
  end

  scope "/", ChatlagWeb do
    pipe_through [:browser]

    get "/", LobbyController, :index
    get "/lobby", LobbyController, :index
    get "/policy", LobbyController, :policy
    get "/chat", LobbyController, :index
    get "/login", AuthController, :login
    get "/details", AuthController, :details
    get "/logout", AuthController, :logout
    post "/login", AuthController, :create
    put "/login", AuthController, :update
    post "/img_uploads", ChatController, :upload
  end

  scope "/", ChatlagWeb do
    pipe_through [:browser, :protected]

    get "/chat/:id", ChatController, :chat
    get "/room/create/:u1/:u2", ChatController, :create_room
  end

  scope "/auth", ChatlagWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/admin", ChatlagWeb do
    pipe_through [:browser, :admin]

    get "/", RoomController, :index
    get "/users/:id/suspend", UserController, :suspend
    get "/users/:id/unsuspend", UserController, :unsuspend
    get "/rooms/:id/del_messages", RoomController, :del_messages
    get "/rooms/:id/messages", RoomController, :messages
    resources "/rooms", RoomController
    resources "/words", WordController
    resources "/contacts", ContactController
    resources "/users", UserController
    get "/reset", RoomController, :ask_reset
    post "/reset", RoomController, :reset
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatlagWeb do
  #   pipe_through :api
  # end
end

lib/chatlag/chat/room.ex
defmodule Chatlag.Chat.Room do
  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset

  schema "rooms" do
    field :min_age, :integer
    field :on_front, :boolean, default: false
    field :is_private, :boolean, default: false
    field :slug, :string
    field :attached, :string
    field :url, :string
    field :bg_color, :string
    field :small_desc, :string
    field :title, :string
    field :slogen, :string
    field :bg_image, ChatlagWeb.DisplayImage.Type
    field :midsize_image, ChatlagWeb.DisplayImage.Type
    field :bg_small_image, ChatlagWeb.DisplayImage.Type
    field :room_icon, ChatlagWeb.DisplayIcon.Type

    timestamps()
  end

  @doc false
  def changeset(room, attrs) do
    attrs = Map.merge(attrs, slug_map(attrs))

    room
    |> cast(attrs, [
      :title,
      :slug,
      :on_front,
      :is_private,
      :small_desc,
      :bg_color,
      :min_age,
      :attached,
      :url,
      :slogen
    ])
    |> cast_attachments(attrs, [:bg_image])
    |> cast_attachments(attrs, [:midsize_image])
    |> cast_attachments(attrs, [:bg_small_image])
    |> cast_attachments(attrs, [:room_icon])
    |> validate_required([:title])
  end

  defp slug_map(%{"title" => title, "slug" => old_slug}) do
    if String.length(old_slug) == 0 do
      slug = String.downcase(title) |> Slugger.slugify()
      %{"slug" => slug}
    else
      %{"slug" => old_slug}
    end
  end

  defp slug_map(_params) do
    %{}
  end
end

lib/chatlag_web/controllers/room_controller.ex
defmodule ChatlagWeb.RoomController do
  use ChatlagWeb, :controller

  import Ecto.Query
  alias Chatlag.Chat
  alias Chatlag.Chat.{Room, Message}
  alias Chatlag.Repo

  def index(conn, params) do
    page =
      Room
      |> order_by(asc: :id)
      |> Repo.paginate(params)

    render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, rooms: page.entries, page: page)
  end

  def new(conn, _params) do
    changeset = Chat.change_room(%Room{})

    render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, changeset: changeset)
  end

  def create(conn, %{"room" => room_params}) do
    case Chat.create_room(room_params) do
      {:ok, _room} ->
        conn
        |> put_flash(:info, "Room created successfully.")
        |> redirect(to: Routes.room_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    room = Chat.get_room!(id)
    render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, room: room)
  end

  def edit(conn, %{"id" => id}) do
    room = Chat.get_room!(id)
    changeset = Chat.change_room(room)
    render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, room: room, changeset: changeset)
  end

  def update(conn, %{"id" => id, "room" => room_params}) do
    room = Chat.get_room!(id)

    case Chat.update_room(room, room_params) do
      {:ok, _room} ->
        conn
        |> put_flash(:info, "Room updated successfully.")
        |> redirect(to: Routes.room_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn,
          layout: {ChatlagWeb.LayoutView, "admin.html"},
          room: room,
          changeset: changeset
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    room = Chat.get_room!(id)
    {:ok, _room} = Chat.delete_room(room)

    conn
    |> put_flash(:info, "Room deleted successfully.")
    |> redirect(to: Routes.room_path(conn, :index))
  end

  def ask_reset(conn, _params) do
    changeset = Chat.change_room(%Room{})

    render(conn, layout: {ChatlagWeb.LayoutView, "admin.html"}, changeset: changeset)
  end

  def messages(conn, params) do
    # params = %{}

    %{"id" => id} = params

    page =
      Message
      |> where(room_id: ^id)
      |> order_by(asc: :id)
      |> Repo.paginate(params)

    IO.inspect(params)
    # conn

    render(conn,
      layout: {ChatlagWeb.LayoutView, "admin.html"},
      messages: page.entries,
      page: page,
      room_id: id
    )
  end

  def reset(conn, _params) do
    conn
    |> put_flash(:info, "Room deleted successfully.")
    |> redirect(to: Routes.room_path(conn, :index))
  end

  def del_messages(conn, %{"id" => id}) do
    msg = Chat.get_message!(id)
    {:ok, _room} = Chat.delete_message(msg)

    conn
    |> put_flash(:info, "Message deleted successfully.")
    |> redirect(to: Routes.room_path(conn, :messages, msg.room_id))
  end
end

lib/chatlag_web/views/room_view.ex
defmodule ChatlagWeb.RoomView do
  use ChatlagWeb, :view
  alias ChatlagWeb.DisplayImage
  alias ChatlagWeb.DisplayIcon

  alias Chatlag.Chat
  alias Chatlag.Users

  import Scrivener.HTML

  def getRoomName(rid) do
    room = Chat.get_room!(rid)
    room.title
  end

  def getRoomBg(id) do
    room = Chat.get_room!(id)

    {room.bg_image, room}
    |> DisplayImage.url()
  end

  def getRoomSmallBg(id) do
    room = Chat.get_room!(id)

    {room.bg_small_image, room}
    |> DisplayImage.url()
  end

  def getRoomMidsizeBg(id) do
    room = Chat.get_room!(id)

    {room.midsize_image, room}
    |> DisplayImage.url()
  end

  def getRoomIcon(id) do
    room = Chat.get_room!(id)

    {room.room_icon, room}
    |> DisplayIcon.url()
  end

  def getUserNickname(uid) do
    user = Users.get_user!(uid)
    user.nickname
  end

  def getUserIcon(uid) do
    user = Users.get_user!(uid)

    if user.image do
      user.image
    else
      if user.role == "admin" do
        "/images/header-logo.png"
      else
        if user.gender == "F" do
          "/images/female.png"
        else
          "/images/male.png"
        end
      end
    end
  end

  def is_image(mtype) do
    case mtype do
      nil ->
        false

      _ ->
        [_, image, _] = Regex.run(~r/(.*)\/(.*)/, mtype)
        image == "image"
    end
  end

  def is_video(mtype) do
    case mtype do
      nil ->
        false

      _ ->
        [_, video, _] = Regex.run(~r/(.*)\/(.*)/, mtype)
        video == "video"
    end
  end
end

lib/chatlag_web/templates/room/ask_reset.html.eex
<br>

<div class="jumbotron">
    <h1 class="display-4">שימו לב!</h1>
    <p class="lead">הינכם עומדים למחוק את כל ההודעות מכל החדרים.</p>
    <hr class="my-4">
    <p>פעולה זו הינה בלתי הפיכה וההודעות ימחקו לנצח כולל כל התמונות והסרטונים.</p>
    <p>כמו כן כל החדרים הפרטיים יעלמו.</p>
    <%= form_for @changeset, Routes.room_path(@conn, :reset), fn f -> %>

    <% cancel = link gettext("Back"), to: Routes.room_path(@conn, :index), class: "btn btn-link" %>
    <%= PBF.submit f, gettext("Delete all messages"), class: "btn-danger", alternative: cancel %>
    <% end %>
</div>

lib/chatlag_web/templates/room/edit.html.eex
<h1><%= gettext("Edit Room") %></h1>

<%= render "form.html", Map.put(assigns, :action, Routes.room_path(@conn, :update, @room)) %>

lib/chatlag_web/templates/room/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
<hr>
<div class="row">
  <div class="col-lg-6">
    <%= PBF.text_input f, :title, label: [text: gettext("Title")] %>
    <%= PBF.text_input f, :slogen, label: [text: gettext("Slogen")] %>
    <%= PBF.text_input f, :attached, label: [text: gettext("Attached")] %>
    <%= PBF.text_input f, :url, label: [text: gettext("Url")] %>
  </div>
  <div class="col-lg-6">
    <%= PBF.text_input f, :min_age, input: [class: "col-lg-2"], label: [text: gettext("min_age")] %>
    <%= PBF.checkbox f, :on_front, label: [text: gettext("on_front")] %>
    <%= PBF.textarea f, :small_desc, label: [text: gettext("small_desc")] %>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <%= PBF.text_input f, :bg_color, input: [class: "col-lg-3"], label: [text: gettext("bg_color")] %>
    <img src="<%= getRoomBg(@room.id) %>" width="200">
    <%= PBF.file_input f, :bg_image, class: "form-control", label: [text: gettext("bg_image")] %>
    <img src="<%= getRoomIcon(@room.id) %>" width="100">
    <%= PBF.file_input f, :room_icon, class: "form-control", label: [text: gettext("room_icon")] %>
  </div>
  <div class="col-lg-6">
    <img src="<%= getRoomSmallBg(@room.id) %>" height="100">
    <%= PBF.file_input f, :bg_small_image, class: "form-control", label: [text: gettext("bg_small_image")] %>
    <img src="<%= getRoomMidsizeBg(@room.id) %>" height="100">
    <%= PBF.file_input f, :midsize_image, class: "form-control", label: [text: gettext("midsize_image")] %>
  </div>
</div>
<% cancel = link gettext("Back"), to: Routes.room_path(@conn, :index), class: "btn btn-link" %>
<%= PBF.submit f, gettext("Save"), class: "btn-primary", alternative: cancel %>
<% end %>

lib/chatlag_web/templates/room/index.html.eex
<h1><%= gettext("Listing Rooms") %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= gettext("Title") %></th>
      <th><%= gettext("Slug") %></th>
      <th><%= gettext("On front") %></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for room <- @rooms do %>
    <tr>
      <td><%= link room.title, to: Routes.room_path(@conn, :edit, room) %></td>
      <td><%= room.slug %></td>
      <td><%= room.on_front %></td>

      <td class="btn-sm">
        <%= link raw("<i class='fas fa-eye'></i>"), to: Routes.chat_path(@conn, :chat, room) %> &nbsp;
        <%= if !room.is_private do %>
        <%= link raw("<i class='far fa-edit'></i>"), to: Routes.room_path(@conn, :edit, room) %>&nbsp;
        <% end %>
        <%= link raw("<i class='fas fa-trash-alt'></i>"), to: Routes.room_path(@conn, :delete, room), method: :delete, data: [confirm: gettext("Are you sure?")] %>
        <%= link raw("<i class='fas fa-list'></i>"), to: Routes.room_path(@conn, :messages, room) %> &nbsp;
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= pagination_links @page %>
<span><%= link gettext("New Room"), to: Routes.room_path(@conn, :new), class: "btn btn-primary" %></span>

lib/chatlag_web/templates/room/messages.html.eex
<h1>
    <%= getRoomName(@room_id) %>
    -
    <%= gettext("Listing chats") %>
</h1>

<table class="table">
    <thead>
        <tr>
            <th><%= gettext("User") %></th>
            <th><%= gettext("Message") %></th>
            <th><%= gettext("Media") %></th>
            <th></th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= for message <- @messages do %>
        <tr>
            <td>

                <img class='profile_picture' alt="user_pic" src="<%= getUserIcon(message.user_id) %>" />
                <%= getUserNickname(message.user_id) %>

            </td>
            <td><%= message.content %></td>
            <td>
                <%= if is_image(message.media_type) do %>
                <img class="chat-media" src="<%= message.media %>" />
                <% end %>

                <%= if is_video(message.media_type) do %>
                <video controls class="chat-media">
                    <source src="<%= message.media %>">
                    Your browser does not support the video tag.
                </video>
                <% end %>

            </td>
            <td class="btn-sm">
                <%= link raw("<i class='fas fa-trash-alt'></i>"), to: Routes.room_path(@conn, :del_messages, message), method: :get, data: [confirm: gettext("Are you sure?")]  %>
                &nbsp;
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<%= pagination_links @page %>

lib/chatlag_web/templates/room/new.html.eex
<h1><%= gettext("New Room")%></h1>

<%= render "new_form.html", Map.put(assigns, :action, Routes.room_path(@conn, :create)) %>

lib/chatlag_web/templates/room/new_form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
  <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<hr>
<div class="row">
  <div class="col-lg-6">
    <%= PBF.text_input f, :title, label: [text: gettext("Title")] %>
    <%= PBF.text_input f, :slogen, label: [text: gettext("Slogen")] %>
    <%= PBF.text_input f, :attached, label: [text: gettext("Attached")] %>
  </div>
  <div class="col-lg-6">
    <%= PBF.text_input f, :min_age, input: [class: "col-lg-2"], label: [text: gettext("min_age")] %>
      <%= PBF.checkbox f, :on_front, label: [text: gettext("on_front")] %>
    <%= PBF.textarea f, :small_desc, label: [text: gettext("small_desc")] %>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <%= PBF.text_input f, :bg_color, input: [class: "col-lg-3"], label: [text: gettext("bg_color")] %>
    
    <%= PBF.file_input f, :bg_image, class: "form-control", label: [text: gettext("bg_image")] %>
    <%= PBF.file_input f, :room_icon, class: "form-control", label: [text: gettext("room_icon")] %>
  </div>
  <div class="col-lg-6">
    <%= PBF.file_input f, :midsize_image, class: "form-control", label: [text: gettext("midsize_image")] %>
    <%= PBF.file_input f, :bg_small_image, class: "form-control", label: [text: gettext("bg_small_image")] %>

  </div>
</div>
<% cancel = link gettext("Back"), to: Routes.room_path(@conn, :index), class: "btn btn-link" %>
<%= PBF.submit f, gettext("Save"), class: "btn-primary", alternative: cancel %>
<% end %>

lib/chatlag_web/templates/room/show.html.eex
<h1>Show Room</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @room.title %>
  </li>

  <li>
    <strong>Slug:</strong>
    <%= @room.slug %>
  </li>

  <li>
    <strong>On front:</strong>
    <%= @room.on_front %>
  </li>

  <li>
    <strong>Small desc:</strong>
    <%= @room.small_desc %>
  </li>

  <li>
    <strong>Min age:</strong>
    <%= @room.min_age %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.room_path(@conn, :edit, @room) %></span>
<span><%= link "Back", to: Routes.room_path(@conn, :index) %></span>