lib/chatlag_web/router.ex
defmodule ChatlagWeb.Router do
  use ChatlagWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlugForwardedPeer
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  pipeline :admin do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :protected do
    plug Chatlag.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
  end

  scope "/", ChatlagWeb do
    pipe_through [:browser]

    get "/", LobbyController, :index
    get "/lobby", LobbyController, :index
    get "/policy", LobbyController, :policy
    get "/chat", LobbyController, :index
    get "/login", AuthController, :login
    get "/details", AuthController, :details
    get "/logout", AuthController, :logout
    post "/login", AuthController, :create
    put "/login", AuthController, :update
    post "/img_uploads", ChatController, :upload
  end

  scope "/", ChatlagWeb do
    pipe_through [:browser, :protected]

    get "/chat/:id", ChatController, :chat
    get "/room/create/:u1/:u2", ChatController, :create_room
  end

  scope "/auth", ChatlagWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/admin", ChatlagWeb do
    pipe_through [:browser, :admin]

    get "/", RoomController, :index
    get "/users/:id/suspend", UserController, :suspend
    get "/users/:id/unsuspend", UserController, :unsuspend
    get "/rooms/:id/del_messages", RoomController, :del_messages
    get "/rooms/:id/messages", RoomController, :messages
    resources "/rooms", RoomController
    resources "/words", WordController
    resources "/contacts", ContactController
    resources "/users", UserController
    get "/reset", RoomController, :ask_reset
    post "/reset", RoomController, :reset
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatlagWeb do
  #   pipe_through :api
  # end
end

lib/chatlag_web/views/layout_view.ex
defmodule ChatlagWeb.LayoutView do
  use ChatlagWeb, :view
end

lib/chatlag_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chatlag</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />

    <style>
        .chat-media {
            /* border: 1px solid gray; */
            width: 8em;
            /* margin: 1em; */
        }
    </style>
</head>

<body>
    <header>
        <section class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a href="<%= Routes.room_path(@conn, :index) %>" class="logo">
                    <img src="<%= Routes.static_path(@conn, "/images/Logo.png") %>" alt="Logo" />
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="pull-right collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <%= link gettext("Lobby"), to: Routes.lobby_path(@conn, :index), class: "nav-link" %></li>
                        <li class="nav-item">
                            <%= link gettext("Rooms"), to: Routes.room_path(@conn, :index), class: "nav-link" %></li>
                        <li class="nav-item">
                            <%= link gettext("Reserved words"), to: Routes.word_path(@conn, :index), class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link gettext("Clear messages"), to: Routes.room_path(@conn, :ask_reset), class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link gettext("users messages"), to: Routes.contact_path(@conn, :index), class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link gettext("users"), to: Routes.user_path(@conn, :index), class: "nav-link" %>
                        </li>
                    </ul>
                </div>
                <div class="pull-left collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <%= link gettext("Logout"), to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "nav-link" %>
                        </li>
                    </ul>
                </div>
            </nav>

        </section>
    </header>
    <main role="main" class="container">
        <%= unless is_nil(get_flash(@conn, :info)) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= unless is_nil(get_flash(@conn, :error)) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>

        <%= render @view_module, @view_template, assigns %>

    </main>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
</body>

</html>

lib/chatlag_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chatlag</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
</head>

<body>
    <div class="container">
        <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
</body>

</html>

lib/chatlag_web/templates/layout/chat.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Chatlag</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1">
    <link rel="stylesheet" type="text/css" <meta name="viewport"
        content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" />
    <link href="<%= Routes.static_path(@conn, "/css/emoji.css ") %>" rel="stylesheet">


    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">

    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css ") %>" />
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/style/chat.css ") %>" />
</head>
<style>
    .xs {
        font-size: small;
    }
</style>

<body>
    <%= render @view_module, @view_template, assigns %>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js ") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/jquery-3.4.1.min.js ") %>'></script>

    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/emoji_config.js ") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/emoji_util.js ") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/jquery.emojiarea.js ") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/emoji-picker.js ") %>'></script>

    <script>
        jQuery(document).ready(function ($) {

            window.emojiPicker = new EmojiPicker({
                emojiable_selector: '[data-emojiable=true]',
                // emojiable_selector: '.chat-msg',
                assetsPath: '/img/',
                popupButtonClasses: 'fa fa-smile-o'
            });

            // window.emojiPicker.discover();

            let $trigger = "";
            let $inImage = false;
            let $image = $("#image_file");

            $("#chatroom-share").click(function (event) {
                $(".menu_share_popup").toggle()
            });

            $("#camera-id").click(function (event) {
                console.log("Click")
                event.preventDefault();
                $('#media_name').val("")
                $trigger = "start";
                $inImage = true;
                $image.focus()
                $image.click()
            });

            $(".image-close").click(function () {
                $('#image-display').hide()
                $('#video-display').hide()
                $('#media_type').val("")
                $('#media_name').val("")
                $('#media_size').val("")

            })

            $("#image_file").change(function () {

                readURL(this);

            });

            $("#image_file").focusout(function () {

                $trigger = "";

            });
            $("#image_file").focusin(function () {

                if ($trigger == "" && $inImage) {
                    if ($('#media_name').val() == "") {
                        $('#enable-click').click()
                        $inImage = false;
                    }
                }


            });
        })

        function readURL(input) {

            var reader = new FileReader();


            $('#image-display').hide()
            $('#video-display').hide()

            $('#media_name').val(input.files[0].name)
            $('#media_size').val(input.files[0].size)
            $('#media_type').val(input.files[0].type)


            // check for valid type

            $type = $('#media_type').val()
            $size = $('#media_size').val()

            if ($type.includes("image") || $type.includes("video")) {

                if ($size < 20 * 1024000 + 1) {
                    reader.onload = function (e) {
                        if ($type.includes("image")) {
                            $('#upload-image-pic').attr('src', e.target.result);
                            $('#image-display').show()
                        } else {
                            if ($type.includes("video")) {
                                $('#upload-video').attr('src', e.target.result);
                                $('#upload-video').attr('type', $type);
                                $('#video-display').show()
                            } else {
                            }
                        }
                        // $('#media_content').val(e.target)

                        var fd = new FormData();
                        var files = input.files[0];
                        var csrf = $('input[name="csrf"]').val();
                        fd.append('file', files);
                        fd.append('_csrf_token', csrf);

                        $.ajax({
                            url: '/img_uploads',
                            type: 'post',
                            data: fd,
                            contentType: false,
                            processData: false,
                            success: function (response) {
                            },
                            error: function (response) {
                                $(".error-msg").html("אירעה שגיאה בעת העלאת הקובץ")
                                $(".error-msg").show()
                                $('#media_type').val("")
                                $('#media_name').val("")
                                $('#media_size').val("")
                            },
                        });

                    }
                    console.log("start upload")
                    reader.readAsDataURL(input.files[0]);
                } else {
                    alert("קובץ גדול מדי. לא ניתן להציג. גודל מקסימלי 20MB")
                    if ($type.includes("image")) {
                        $("#upload-image-pic").hide();
                        $('#image-display').show()
                    }
                    if ($type.includes("video")) {
                        $("#video-tag").hide();
                        $('#video-display').show()
                    }
                    // $(".error-msg").html("קובץ גדול מדי. לא ניתן להציג. גודל מקסימלי 20MB")
                    $(".error-msg").show()
                    $('#media_type').val("")
                    $('#media_name').val("")
                    $('#media_size').val("")
                }
            } else {
                alert("סוג קובץ זה לא נתמך על ידי המערכת")
                $('#media_name').val("")
                $('#media_size').val("")
                $('#media_type').val("")

                $('#upload-image-pic').attr('src', '');

            }
            $inImage = false;
        }

        function startUpload(formData) {

            jQuery.ajax({
                type: 'POST',
                url: '/img_uploads',

                data: formData,
                processData: true, //IMPORTANT!

                cache: false,
                contentType: false,



                success: function (data) {
                    console.log("SUCCESS", data)
                },

                error: function (data) {
                    console.error(data);
                }
            })
        }
    </script>
</body>

</html>

lib/chatlag_web/templates/layout/empty.html.eex
<%= render @view_module, @view_template, assigns %>

lib/chatlag_web/templates/layout/front.html.eex
<!doctype html>
<html lang="he">

<head>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>פורטל הצ'אטים הגדול בארץ</title>
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/jquery-3.4.1.min.js") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/swiped-events.js") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/bootstrap.min.js") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/scale.js") %>'></script>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/script.js") %>'></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, " /css/app.css ") %>" />
    <link href='<%= Routes.static_path(@conn, "/css/lobby-style.css") %>' rel="stylesheet" type="text/css">
    <style>
        a {
            color: black;
        }
    </style>

</head>

<body>
    <%= render @view_module, @view_template, assigns %>
</body>

</html>

lib/chatlag_web/templates/layout/login.html.eex
<!doctype html>
<html lang="he">

<head>
    <meta charset="utf-8">
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#08dfab">
    <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#08dfab">
    <title>התחברות - פורטל הצ'אטים הגדול בארץ</title>
    <link href="/style/bootstrap-custom.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/earlyaccess/opensanshebrew.css" rel="stylesheet" type="text/css">
    <link href="/style/login-style.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="/script/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="/script/login-script.js"></script>
</head>

<body>
    <%= render @view_module, @view_template, assigns %>
</body>

<script>
    function rudr_favorite(a) {
        pageTitle = document.title;
        pageURL = document.location;
        try {
            // Internet Explorer solution
            eval("window.external.AddFa-vorite(pageURL, pageTitle)".replace(/-/g, ''));
        } catch (e) {
            try {
                // Mozilla Firefox solution
                window.sidebar.addPanel(pageTitle, pageURL, "");
            } catch (e) {
                // Opera solution
                if (typeof (opera) == "object") {
                    a.rel = "sidebar";
                    a.title = pageTitle;
                    a.url = pageURL;
                    return true;
                } else {
                    // The rest browsers (i.e Chrome, Safari)
                    alert('לחצו ' + (navigator.userAgent.toLowerCase().indexOf('mac') != -1 ? 'Cmd' : 'Ctrl') + '+D על מנת להוסיף למועדפים.');
                }
            }
        }
        return false;
    }
</script>

</html>